name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # This triggers deployment on every push to 'main' branch

jobs:
  deploy:
    name: Build & Deploy to Cloud Run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: stockml-452722

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/stockml-452722/stockml-repo/stock-api .
          docker push us-central1-docker.pkg.dev/stockml-452722/stockml-repo/stock-api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy stock-api \
            --image us-central1-docker.pkg.dev/stockml-452722/stockml-repo/stock-api \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --memory=1Gi
